import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MenuBar from "./components/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body className={inter.className}>
    <main className="flex">
      <div className="w-[20%] hidden md:block sm:block lg:block ">
        <MenuBar />
      </div>
      <div className="container ">{children}</div>
    </main>
  </body>
</html>

  );
}
